
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://localhost:5432/flais_layout_config_service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus