spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  profiles:
    include:
      - db
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus